### ISSUE TITLE
Cannot read property 'require' of null

### ISSUE THREAD

**Issue by GreenMonkeyBoy** [mflorence99/el-term#2]
Hi, I followed the steps to install it, but i got this error in dev and prod mode (the app remains stuck on the clock icon):

`TypeError: Cannot read property 'require' of null
    at new TerminalService (terminal.ts:26)
    at _createClass (core.js:9275)
    at _createProviderInstance$1 (core.js:9255)
    at resolveNgModuleDep (core.js:9221)
    at _createClass (core.js:9275)
    at _createProviderInstance$1 (core.js:9255)
    at resolveNgModuleDep (core.js:9221)
    at NgModuleRef_.push.../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9919)
    at _loop_1 (ngxs-store.js:655)
    at StateFactory.push.../node_modules/@ngxs/store/fesm5/ngxs-store.js.StateFactory.add (ngxs-store.js:668)`

Tested on Linux Ubuntu and Node 10.0.0.

**Comment by mflorence99** [comment]
Thanks for checking it out and I'm sorry you are having trouble! I have not seen this issue before. The stack trace points to the first use of https://github.com/ThorstenHans/ngx-electron. 

```typescript
this.nodePty = this.electron.remote.require('node-pty');
```
If it detects that you're *not* running under Electron, it sets all its `electron` references to null. I can't see how that could be in your case, unless you tried to launch the app from the browser, instead of Electron -- from http://localhost:4200 in other words.

Assuming that's not so, I will say that I haven't tested under Node v10. I'll see what I can do there.

If you have a Node v8 sitting around I'd be very grateful if you could test there, if you get there before I do.

Thanks again!

**Comment by GreenMonkeyBoy** [comment]
Node 10.0.0 (npm 5.6.0) : Error
Node 9.0.0 (npm 5.5.1): Error
Node 8.9.0 (npm 5.5.1): Works

Yesterday I only tried Node 10 and 9, I should keep trying others versions. So the error appears at least on 9.0.0 and 10.0.0, but the version 8.9.0 (the minimum for angular 6) works fine.

All tests are on Linux Ubuntu 16.04.

**Comment by GreenMonkeyBoy** [comment]
Ok I resolved the problem using electron-rebuild. The electron modules needed to be rebuild (I don't know why, I don't use electron).

I removed my el-term folder, switch to Node 10.0.0, cloned your project, installed and run, the app stills remained stuck on the clock icon.

So I first installed electron-debug to open the dev tools and read the error:
> Error: The module '/home/gmb/dev/el-term/node_modules/node-pty/build/Release/pty.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
> the module (for instance, using `npm rebuild` or `npm install`) etc.

I tried to delete the node_modules, install them again, rebuild them... nothing worked. Then I found [this issue](https://github.com/electron/electron/issues/10858).

Installing [electron-rebuild](https://github.com/electron/electron-rebuild) and running this command have resolved the problem: 

> ./node_modules/.bin/electron-rebuild

Now I can use your terminal, I have tried tmux 6 months ago but it was hard to split and resize the panes using commands, so I stopped using it, but your project is a lot more intuitive and ergonomic. Good job.

**Comment by mflorence99** [comment]
Hey many thanks for that research and for your kind comments! My apologies that you are ahead of me. I will upgrade my dev system to Node v10 and incorporate electron-rebuild into my workflow and into the launch instructions. I'm pretty sure now that I can use a `postinstall` target in the `package.json` to perform the rebuild automatically. Thanks again!
